name: Auto Review

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  auto-review:
    runs-on: ubuntu-latest

    steps:
    - name: Auto Review
      uses: Dvs-git/calcom
      with:
        reviewers: Dvs-git
